[client]
showSidebarNavigation = false

[theme]
primaryColor = "#2563EB"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#0F172A"
textColor = "#1E293B"
font = "sans serif"

[logger]
level = "info"
